version: '3.8'

services:
  storage_found:
    build:
      context: .
      target: storage
    restart: always
    environment:
      PORT: 5000
    ports:
      - "5000:5000"

  storage_lost:
    build:
      context: .
      target: storage
    restart: always
    environment:
      PORT: 5001
    ports:
      - "5001:5001"

  storage_found_watcher:
    build:
      context: .
      target: storage
    restart: always
    environment:
      PORT: 5002
    ports:
      - "5002:5002"

  telegram-bot:
    depends_on:
      - storage_found
      - storage_lost
      - storage_found_watcher
    build:
      context: .
      target: telegram-bot
    environment:
      FOUND_STORAGE_URL: "http://storage_found:5000"
      LOST_STORAGE_URL: "http://storage_lost:5001"
      EMBEDDING_MODEL_PATH: "models/facenet150.h5"
